% function [xps,xas,Pxxps,Pxxas,par_means,par_vars] =...
%   KF(KF_choice,KF_model_func,KF_exp_func,KF_meas_func,KF_ic_state_func,...
%   KF_ic_params_func,KF_meas_addl_info,KF_ic_state_addl_info,KF_ic_params_addl_info,...
%   KF_noise_addl_info,KF_time_info,KF_options_cell,problem_location)
close all;

%%  Linear/extended KF
%  We can't use the linear/extended KF with the cell migration code because
%  we don't have a jacobian

%%  Use approximate solution for the diff eqs for the measurements
%  SC KF simulated data
%[xfs,xas,Pxxas,vs] =...
%  KF('SC_KF',@model_func_cm,@exp_func_cm,@meas_func_cm,...
%  @ics_for_state_func_cm,@ics_for_params_func_cm,...
%  {},{'g.nx',10,'ht.type','circle'},{'D.initial_guess',0.5e-3,'stddev_frac',sqrt(0.1)},...
%  {'noise_frac',1,'model_state_noise',1e-6,...
%  'ini_state_noise',.003,'meas_noise',.003},...
%  {'expts',linspace(0,0.02,21),'bump_size',0},{'fig_nums',[1],'q',1000},...
%  'Porous_Folder');

%%  Use approximate solution for the diff eqs for the measurements
%  SC KF experimental data
%[xfs,xas,Pxxas,vs] =...
%  KF('SC_KF',@model_func_cm,@exp_func_cm,@meas_func_cm,...
%  @ics_for_state_func_cm,@ics_for_params_func_cm,...
%  {},{'g.nx',10,'ht.type','circle'},{'D.initial_guess',0.5e-3,'stddev_frac',0.1},...
%  {'noise_frac',1,'model_state_noise',1e-6,...
%  'ini_state_noise',.003,'meas_noise',.003},...
%  {'expts',linspace(0,0.02,21),'bump_size',0},{'em',1,'fig_nums',[1],'q',1000},...
%  'Porous_Folder');

%%  Use approximate solution for the diff eqs for the measurements
%  En KF simulated data
[xfs,xas,Pxxas,vs] =...
  KF('En_KF',@model_func_cm,@exp_func_cm,@meas_func_cm,...
  @ics_for_state_func_cm,@ics_for_params_func_cm,...
  {},{},{'D.initial_guess',1.5e-3,'stddev_frac',0.1},...
  {'noise_frac',1,'model_state_noise',1e-3,...
  'ini_state_noise',.001,'meas_noise',.001},...
  {'expts',linspace(0,0.25,100),'bump_size',0},{'fig_nums',[1],'q',1000},...
  'Porous_Folder');

%%  Use approximate solution for the diff eqs for the measurements
%  SC SVD KF simulated data
%[xfs,xas,Pxxas,vs] =...
%  KF('SC_SVD_KF',@model_func_cm,@exp_func_cm,@meas_func_cm,...
%  @ics_for_state_func_cm,@ics_for_params_func_cm,...
%  {},{'g.nx',10,'ht.type','circle'},{'D.initial_guess',0.5e-3,'stddev_frac',0.1},...
%  {'noise_frac',1,'model_state_noise',1e-6,...
%  'ini_state_noise',.003,'meas_noise',.003},...
%  {'expts',linspace(0,0.02,21),'bump_size',0},{'fig_nums',[1],'q',1000},...
%  'Porous_Folder');